### ISSUE TITLE
Cannot start gulp process; dependancy issue?

### ISSUE THREAD

**Issue by mikefraser** [vigetlabs/gulp-starter#236] opened 2016-01-14 16:59 UTC
Hi, I'm having no luck get this installed and running.
I'm using node 0.12.2, npm 2.7.4.
running ````npm run gulp```` spits out the following npm-debug.log:

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'gulp' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info pregulp gulp-starter@2.2.0
6 info gulp gulp-starter@2.2.0
7 verbose unsafe-perm in lifecycle true
8 info gulp-starter@2.2.0 Failed to exec gulp script
9 verbose stack Error: gulp-starter@2.2.0 gulp: `gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid gulp-starter@2.2.0
11 verbose cwd /home/admin/web/dev.slrweb.xyz/public_html/1_SLR_Mapping/working
12 error Linux 3.13.0-71-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error gulp-starter@2.2.0 gulp: `gulp`
17 error Exit status 1
18 error Failed at the gulp-starter@2.2.0 gulp script 'gulp'.
18 error This is most likely a problem with the gulp-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get their info via:
18 error     npm owner ls gulp-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
````

Any ideas? Thanks!

**Comment by greypants** [comment] 2016-01-15 13:50
Hmm... looks like the same issue as #228 

All I can think of is maybe there's a breaking change a dependency with a minor version change. Try removing all the `^` from package.json so you're specifying exact version numbers, `rm -rf node_modules` then run npm install again and let me know what you get.

**Comment by mikefraser** [comment] 2016-01-15 23:23
Ok... Updated debug as follows:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'gulp' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info pregulp gulp-starter@2.2.0
6 info gulp gulp-starter@2.2.0
7 verbose unsafe-perm in lifecycle true
8 info gulp-starter@2.2.0 Failed to exec gulp script
9 verbose stack Error: gulp-starter@2.2.0 gulp: `gulp`
9 verbose stack Exit status 127
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid gulp-starter@2.2.0
11 verbose cwd /home/admin/web/dev.slrweb.xyz/public_html/2_MJF_Gulptests
12 error Linux 3.13.0-71-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error gulp-starter@2.2.0 gulp: `gulp`
17 error Exit status 127
18 error Failed at the gulp-starter@2.2.0 gulp script 'gulp'.
18 error This is most likely a problem with the gulp-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get their info via:
18 error     npm owner ls gulp-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
````
If it's any help, terminal spits out the following when I run NPM install:
````
pm WARN deprecated gulp-minify-css@1.2.0: Please use gulp-cssnano instead.
npm WARN deprecated babel-core@5.8.3: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN optional dep failed, continuing fsevents@1.0.6
Killed
````
Thanks btw!

**Comment by greypants** [comment] 2016-03-22 14:49
I locked down exact dependencies in my `package.json` file to eliminate some variables. Did you ever get this working? Can you try again with the latests from `master`?

Closing this as a duplicate of #228

**Closed by greypants** 2016-03-22 14:49 UTC
